# Numpy Cheat Sheet

## Numpy


The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [1]:
# Import convention
import numpy as np

## Creating Arrays

In [2]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1),(4,5,6)]], dtype = float)

### Initial Placeholders

In [3]:
np.zeros((3,4)) #Create an array of zeros
np.ones((2,3,4),dtype=np.int16) #Create an array of ones
d = np.arange(10,25,5) #Create an array of evenly spaced values (step value)
np.linspace(0,2,9) #Create an array of evenly spaced values (number of samples)
e = np.full((2,2),7) #Create a constant array
f = np.eye(2) #Create a 2X2 identity matrix
np.random.random((2,2)) #Create an array with random values
np.empty((3,2)) #Create an empty array

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

## I/O

### Saving & Loading On Disk

In [4]:
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')

array([1, 2, 3])

### Saving & Loading Text Files

In [5]:

np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
np.savetxt("myarray.txt", a, delimiter=" ")

/var/folders/fw/lfwqgrwx72v8gqhx3vm2nv780000gn/T/ipykernel_809/1365320612.py:1: UserWarning: loadtxt: input contained no data: "myfile.txt"
  np.loadtxt("myfile.txt")
/var/folders/fw/lfwqgrwx72v8gqhx3vm2nv780000gn/T/ipykernel_809/1365320612.py:2: UserWarning: genfromtxt: Empty input file: "my_file.csv"
  np.genfromtxt("my_file.csv", delimiter=',')


## Asking For Help

In [6]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## Inspecting Your Array

In [7]:
a.shape
len(a)
b.ndim #Number of array dimensions
e.size #Number of array elements
b.dtype #Data type of array elements
b.dtype.name #Name of data type
b.astype(int) #Convert an array to a different type


array([[1, 2, 3],
       [4, 5, 6]])

## Data Types

In [8]:
np.int64 #Signed 64-bit integer types
np.float32 #Standard double-precision floating point
#metodos depreciados:
#np.complex #Complex numbers represented by 128 floats
#np.bool #Boolean type storing TRUE and FALSE values Numpy
#np.object #Python object type
np.string_ #Fixed-length string type
np.unicode_ #Fixed-length unicode type


numpy.str_

## Array Mathematics#

### Arithmetic Operations

In [9]:
g = a - b #Subtraction
np.subtract(a,b) #Subtraction
b + a #Addition
np.add(b,a) #Addition
a / b #Division
np.divide(a,b) #Division
a * b #Multiplication
np.multiply(a,b) #Multiplication
np.exp(b) #Exponentiation
np.sqrt(b) #Square root
np.sin(a) #Print sines of an array
np.cos(b) #Element-wise cosine
np.log(a) #Element-wise natural logarithm
e.dot(f) #Dot product

array([[7., 7.],
       [7., 7.]])

### Comparison

In [10]:
a == b #Element-wise comparison
a < 2 #Element-wise comparison
np.array_equal(a, b) #Array-wise comparison

False

### Aggregate Functions

In [11]:
a.sum() #Array-wise sum
a.min() #Array-wise minimum value
b.max(axis=0) #Maximum value of an array row
b.cumsum(axis=1) #Cumulative sum of the elements
a.mean() #Mean
np.median(b) #Median
np.corrcoef(a) #Correlation coefficient
np.std(b) #Standard deviation

1.5920810978785667

## Copying Arrays

In [12]:
h = a.view() #Create a view of the array with the same data
np.copy(a) #Create a copy of the array
h = a.copy() #Create a deep copy of the array

## Sorting Arrays

In [13]:
a.sort() #Sort an array
c.sort(axis=0) #Sort the elements of an array's axis

## Subsetting, Slicing, Indexing

In [14]:
#Subsetting
a[0:2] #Select the element at the 2nd index
b[1,2] #Select the element at row 1 column 2 (equivalent to b[1][2])
#Slicing
a[0:2] #Select items at index 0 and 1
b[0:2,1] #Select items at rows 0 and 1 in column 1
b[:1] #Select all items at row 0 (equivalent to b[0:1, :])
c[1,...] #Same as [1,:,:]
a[ : :-1] #Reversed array a array([3, 2, 1])
#Boolean Indexing
a[a<2] #Select elements from a less than 2
#Fancy Indexing
b[[1, 0, 1, 0],[0, 1, 2, 0]] #Select elements (1,0),(0,1),(1,2) and (0,0)
b[[1, 0, 1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns


array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## Array Manipulation

In [15]:
#Transposing Array
i = np.transpose(b) #Permute array dimensions
i.T #Permute array dimensions
#Changing Array Shape
b.ravel() #Flatten the array
g.reshape(3,-2) #Reshape, but don’t change data
#Adding/Removing Elements
h.resize((2,6)) #Return a new array with shape (2,6)
np.append(h,g) #Append items to an array
np.insert(a, 1, 5) #Insert items in an array
np.delete(a,[1]) #Delete items from an array
#Combining Arrays
a=np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1),(4,5,6)]], dtype = float)
np.concatenate((a,d),axis=0) #Concatenate arrays
np.vstack((a,b)) #Stack arrays vertically (row-wise)
np.r_[e,f] #Stack arrays vertically (row-wise)
np.hstack((e,f)) #Stack arrays horizontally (column-wise)
np.column_stack((a,d)) #Create stacked column-wise arrays
np.c_[a,d] #Create stacked column-wise arrays
#Splitting Arrays
np.hsplit(a,3)

[array([1]), array([2]), array([3])]